### ISSUE TITLE
Announcer mode

### ISSUE THREAD

**Issue by singpolyma** [capnmidnight/Calla#101] opened 2020-10-09 00:00 UTC
For meetups, it would be very useful if there could be a "stage" or an "announcer mode" that would allow switching between "go all talk amongst yourselves" and "now hear this" presentation time.  Basically a button that would allow someone to say something to the whole map regardless of position.

**Comment by capnmidnight** [comment] 2020-10-09 00:06
This is kind of a duplicate of issue #6 

I closed that issue because... well, I don't really know. I want this repo to just be the library for working with spatialized audio on Jitsi. The "game" app is mostly just a demonstrator of that library. I don't have a lot of interest in running the "game" app as a meeting service itself, and would ideally split it out to a completely separate repo. But I've not had the time in the last few weeks to make the full transition over.

The issue of having an announcer button would fit more with an interface issue of enhancing the "game" app. I don't think the library would need any changes. Maybe it would, but it would make the most sense to make the feature request start with the game to discover if there were any changes needed to the library.

Once I get my next milestone for my project at work done (which is using Calla, so I'm still working on Calla), then I'll have more time to work on those issues.

I'll leave this open for now.

**Comment by capnmidnight** [comment] 2022-03-25 18:43
archiving

**Closed by capnmidnight** 2022-03-25 18:43 UTC
Labels: enhancement
