### ISSUE TITLE
error when import in reactjs

### ISSUE THREAD

**Issue by manang** [capnmidnight/Calla#110] opened 2020-11-07 13:26 UTC
Hi,
I'm trying to import calla.js in a reactjs project and I obtain the following error:

`  Line 2931:17:   'bData' is not defined                               no-undef
  Line 3586:13:   'mode' is not defined                                no-undef
  Line 4266:30:   'ambisonicOrder' is not defined                      no-undef
  Line 4507:13:   'mode' is not defined                                no-undef
  Line 6631:13:   'options' is not defined                             no-undef
  Line 6635:13:   'options' is not defined                             no-undef
  Line 6640:13:   'options' is not defined                             no-undef
  Line 6642:9:    'options' is not defined                             no-undef
  Line 20060:38:  'define' is not defined                              no-undef
  Line 20061:2:   'define' is not defined                              no-undef
  Line 21003:58:  'x' is not defined                                   no-undef
  Line 21003:61:  'y' is not defined                                   no-undef
  Line 21003:64:  'z' is not defined                                   no-undef`

do you have a solution for this error?
thanks

**Comment by capnmidnight** [comment] 2020-11-09 02:52
#111 is a duplicate of this, but that was where the discussion went, so I'm closing this one. Please close 111 when you feel satisfied the issue is fixed.

**Closed by capnmidnight** 2020-11-09 02:52 UTC
