### ISSUE TITLE
No "<" visible to get to "raw" jitsi interface

### ISSUE THREAD

**Issue by yarikoptic** [capnmidnight/Calla#41] opened 2020-04-30 16:27 UTC
README says

> If you need to change your microphone settings, click the < arrow in the menu in the upper right corner of the window to hide the map view and give you full access to the Jitsi Meet interface.

and IIRC it was there.  But now for me I just have a menu bar on top and I found no way to hide away Calla interface and get into "raw" jitsi.

Here is how it looks for me:
![DeepinScreenshot_select-area_20200430122559](https://user-images.githubusercontent.com/39889/80734871-d558e600-8add-11ea-9b4b-b17708d70994.png)

using chromium Version 79.0.3945.130 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)

**Comment by capnmidnight** [comment] 2020-04-30 16:29
Ah, README is out of date. If you need to change your microphone/speaker settings, there are selectors in Calla's own Options view now.

Were there other settings you needed to get to?

**Comment by yarikoptic** [comment] 2020-04-30 16:31
ah -- but then how do I hide a map and interact with jitsi UI itself? e.g. click on options for others, or initiate screen sharing etc...  I thought that idea for the map is just to establish "neighborhood" but then to interact with jitsi normally

**Comment by capnmidnight** [comment] 2020-04-30 16:58
At least for my purposes, that's not really the idea. Ideally, you shouldn't have to interact with Jitsi at all. Calla should expose every "useful" Jitsi option through Calla's own interface. 

Whenever one of us gets around to implementing Issue #33, then the default Jitsi interface will go away completely. Without it, there would be no way for users to choose if they want to watch any particular video feed. So if you have multiple conversations going on in different parts of the map, Jitsi is going to start showing the video from whomever is the loudest to all users.

When that is complete, then Issue #39 can be implemented, followed by an option to select a user's video feed to render modally on top of the map. There is also Issues #6 and #32 , which we've discussed adding an "exclusive presenter mode" tile for maps, so that a lectern or podium could be designated if people are creating a conference experience.

I'm torn on whether or not Video is actually useful. I personally don't like Video calls, I think the video is distracting and you never actually get the "face-to-face" feel because nobody can look into their camera and at their computer screen at the same time. I've had better "face-to-face" feel with avatars in VR chat apps than I've ever had in video calls. I'd like to encourage people to explore more options with avatars than to default to video.

Also, video bandwidth is expensive. Please don't use video on the calla.chat domain. I'm paying for that out of my own pocket.

On screensharing, I've found it to be pretty buggy with Jitsi, locking up my entire browser process. I've done WebRTC screensharing in the past and it worked fine, but that was some years ago, so I don't know if this is an issue with Jitsi or a regression in Chromium. 

With the greater control over video feeds that implementing lib-jitsi-meet would provide, I'd like to revisit screensharing, as then it would just be the video feed presented per-user and users could choose to view it if they wanted. Might even make for a nice UX to have rooms in-map for screensharing, and then users could zoom in to see the screen better.

**Comment by capnmidnight** [comment] 2020-04-30 16:59
I'll add a "Show Jitsi" button back in for provisional use until these other issues are addressed, but I'll probably make it small and out of the way.

**Comment by yarikoptic** [comment] 2020-04-30 17:59
oh, thanks for the detailed answer describing ongoing work and ideas and use-cases you have in mind! Very helpful!
I wanted to ask in a separate issue, but may be you would not mind if I just continue here for now.  On "video" aspect - I wondered if there plans to "integrate" with/in https://jitsi.org/jitsi-videobridge/ ? I guess making it possible to select video streams to be mixed in based on some distance cut off.

> Please don't use video on the calla.chat domain

Thanks for the warning! I might try if only briefly (I hope it is ok) just to see if Calla version works for me, but then will try to roll out my own installation of [Calla using the instructions you point to in README](https://github.com/capnmidnight/Calla#server).

**Comment by capnmidnight** [comment] 2020-04-30 19:15
Honestly, I know very little about Jitsi itself. I figured out how to hack on their IFrame-based API for integrating Jitsi Meet into an existing webpage. I'll learn more about lib-jitsi-meet when I build Issue #33, but anything related to how the backend operates is waaaaay outside my knowledge domain.

That said, it sounds like a great idea. So... ¯\_(ツ)_/¯ (**hint**this project is open for contribution**hint**)

On setting up your own instance, don't forget the notes in https://github.com/capnmidnight/Calla#installation

Though, once Issue #33 is implemented, the installation will be easier and not require editing any files in the Jitsi Meet install. Unfortunately, I don't know when that will happen, as I kinda took a month off from my real job to make Calla (weeell, it's not completely unrelated, I make VR software and I've been evaluating Jitsi as the voice chat backend for an app we're making) and need to get back to being productive there.

**Comment by capnmidnight** [comment] 2020-04-30 19:28
Oh, and on the bandwidth issue, tests here and there are certainly fine. Right now, I'm trending to end up spending about 2x over my normal monthly server costs (from $50 USD to $150 USD, though that first $50 is also paying for my Visual Studio Pro subscription). I end up running my own ~7 - 10 user meetings about once a week. The biggest hit was from the project hitting the Hacker News front page for half a day.

I'm setup on Azure with a small server (2 vcpus, 4gb ram). I don't know what it would cost on some other platform. What I've seen of AWS pricing, it'd be more expensive. Maybe Issue #33 would help in that one might be able to use 8x8's own Jitsi servers. IDK if that's possible with lib-jitsi-meet (it is with their IFrame API, they just ask you don't hide their logo), or if they'd be cool with that. Definitely don't want to be biting the hand that feeds me, especially when it's another OSS project.

Honestly, I'm a little bit out of my depth with the longer-term prospects of this project. I really expected that HN post to get ignored, like all my other projects. And unlike when I was building those other projects, I have a day job that I love. So managing this project is definitely going to take finding some folks to help out. I get people emailing me at random asking if I'm going to seek VC funding. Only if there are other people active on the coding, so I can pay *them* and keep my day job!

**Comment by yarikoptic** [comment] 2020-04-30 19:53
Thanks again for all the details.  Hopefully also other contributors indeed would join to help. Unfortunately myself I have no clue in JS, can only contribute my whining ;)

> I'll add a "Show Jitsi" button back in for provisional use until these other issues are addressed, but I'll probably make it small and out of the way.

Thanks in advance!  If you could ping me here whenever it is done to test again/more -- would be greatly appreciated!

**Comment by capnmidnight** [comment] 2020-04-30 19:55
You should get a notification when I close this issue, which I will do when the README is updated and the button is added.

**Comment by yarikoptic** [comment] 2020-04-30 19:55
cool, thanks! (thought it might be closed just by tune up to README ;))

**Comment by capnmidnight** [comment] 2020-05-11 22:18
Okay, this is ready

**Closed by capnmidnight** 2020-05-11 22:18 UTC
Labels: bug, documentation
